[loggers]
keys=root,flask,pizzaparty

[handlers]
keys=consoleHandler,fileHandler,errorFileHandler

[formatters]
keys=standard,detailed

[logger_root]
level=DEBUG
handlers=consoleHandler,fileHandler,errorFileHandler

[logger_flask]
level=INFO
handlers=consoleHandler,fileHandler
qualname=flask
propagate=1

[logger_pizzaparty]
level=DEBUG
handlers=consoleHandler,fileHandler,errorFileHandler
qualname=pizzaparty
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=standard
args=(sys.stdout,)

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=detailed
args=('pizzaparty.log', 'a')

[handler_errorFileHandler]
class=FileHandler
level=CRITICAL
formatter=detailed
args=('pizzaparty_errors.log', 'a')

[formatter_standard]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=%Y-%m-%d %H:%M:%S

[formatter_detailed]
format=%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(funcName)s() - %(message)s
datefmt=%Y-%m-%d %H:%M:%S
